import{S as w,N as C,K as B,a as q,b as k,i as h}from"./assets/vendor-d6656f63.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const p of s.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&c(p)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const O=document.querySelector(".projects__button--prev-js"),P=document.querySelector(".projects__button--next-js"),b=document.querySelector(".reviews-swiper-wrapper"),E=document.querySelector(".reviews-prev-btn"),L=document.querySelector(".reviews-next-btn"),x=document.querySelector("#covers"),S=document.querySelector(".covers-background"),v=document.querySelector(".covers-wrapper"),N=document.querySelector(".mobile-menu-btn"),d=document.querySelector(".modal"),T=document.querySelector(".close-menu-btn"),D=document.querySelector(".menu-btn"),f=document.querySelector(".menu-list"),I=document.body,y=document.querySelector(".footer-form-feedback"),n=document.querySelector(".footer-input-email"),i=document.querySelector(".footer-input-comment"),a=document.querySelector(".footer-btn"),l=document.querySelector(".wrongEmail"),u=document.querySelector(".wrongComment"),g=document.querySelector(".btnToTop");w.use([C,B]);new w(".projects__swiper-container",{keyboard:{enabled:!0,onlyInViewport:!1},direction:"horizontal",slidesPerView:1,spaceBetween:280,navigation:{nextEl:P,prevEl:O}});async function $(){try{return(await q.get("https://portfolio-js.b.goit.study/api/reviews")).data}catch(e){return console.error(e),null}}async function M(){try{const e=await $();if(!e){b.innerHTML="<li>Not Found</li>";return}const o=e.map(r=>`
        
      <li class="swiper-slide reviews-swiper-slide">
          <img src="${r.avatar_url}" 
          loading="lazy" alt="${r.author}" 
          class="reviews-img" 
          width="48" height="48">
          <div class = "reviews-desc">
          <h3 class="reviews-item-subtitle">${r.author}</h3>
        <div class="reviews-text">${r.review}</div>
        </div>
      </li>
    `).join("");b.innerHTML=o}catch(e){console.error(e)}}async function V(){await M(),new w(".reviews-section .swiper-reviews",{modules:[C,B],spaceBetween:16,pageUpDown:!0,mousewheel:!0,navigation:{prevEl:E||void 0,nextEl:L||void 0},allowTouchMove:!0,breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}},keyboard:{enabled:!0,onlyInViewport:!0}})}V();v.addEventListener("click",A);function _(e){e.forEach(o=>{o.isIntersecting?(S.classList.add("animated"),v.classList.add("animated")):(S.classList.remove("animated"),v.classList.remove("animated"))})}const j=new IntersectionObserver(_,{root:null,threshold:0});j.observe(x);function A(e){if(e.preventDefault(),e.target.nodeName!=="IMG")return;const o=e.target.currentSrc,r=k.create(`<img
      src="${o}"
      alt="${e.target.alt}"
      class="covers-full-image"
    />`,{onShow:t=>{window.addEventListener("keydown",c)},onClose:t=>{window.removeEventListener("keydown",c)}});r.show();function c(t){t.code==="Escape"&&r.close()}}N.addEventListener("click",()=>{d.classList.toggle("is-open"),I.classList.toggle("no-scroll")});T.addEventListener("click",()=>{d.classList.remove("is-open"),I.classList.toggle("no-scroll")});d.addEventListener("click",e=>{e.target.nodeName==="A"&&d.classList.remove("is-open")});D.addEventListener("click",()=>{f.classList.toggle("is-open")});f.addEventListener("click",e=>{e.target.nodeName==="A"&&f.classList.remove("is-open")});const U="https://portfolio-js.b.goit.study/api";async function F(e){try{return(await q.post(`${U}/requests`,e)).data}catch(o){throw o}}document.addEventListener("DOMContentLoaded",()=>{if(n&&i&&y&&a){n.addEventListener("input",z),i.addEventListener("input",J),y.addEventListener("submit",R);const e=JSON.parse(localStorage.getItem("savedUserInput"));e&&(n.value=e.email,i.value=e.comment),m()}else console.error("One or more elements are not found in the DOM.")});function z(){!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(n.value)||n.value.trim().length<=0?(n.style.borderBottomColor="#E74A3B",l.style.color="#E74A3B",l.textContent="Invalid email, try again"):(n.style.borderBottomColor="#3CBC81",l.style.color="#3CBC81",l.textContent="Success!"),m()}function J(){i.value.trim().length<=0?(i.style.borderBottomColor="#E74A3B",u.style.color="#E74A3B",u.textContent="Please, fill the field"):(i.style.borderBottomColor="#3CBC81",u.style.color="#3CBC81",u.textContent="Success!"),m()}function m(){const o=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(n.value)&&n.value.trim().length>0,r=i.value.trim().length>0;o&&r?(a.disabled=!1,a.style.backgroundColor=""):(a.disabled=!0,a.style.backgroundColor="#3B3B3B"),K()}function K(){const e={email:n.value.trim(),comment:i.value.trim()};localStorage.setItem("savedUserInput",JSON.stringify(e))}async function R(e){e.preventDefault();const o=JSON.parse(localStorage.getItem("savedUserInput"));try{await F(o),h.show({theme:"dark",class:"toastStyle",title:"Thank you for your interest in cooperation!",message:"The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.",position:"center",timeout:0,close:!0,backgroundColor:"rgba(28,29,32,1)",overlay:!0,overlayColor:"rgba(0, 0, 0, 0.6)",progressBar:!1,closeOnEscape:!0,closeOnClick:!1,overlayClose:!0}),y.reset(),localStorage.removeItem("savedUserInput"),m()}catch(r){h.show({class:"izi",title:"Error",message:`Error: ${r.message}`,position:"center",progressBar:!1,closeOnEscape:!0,closeOnClick:!0,timeout:0})}}window.addEventListener("scroll",()=>{window.scrollY>100?g.classList.add("show"):g.classList.remove("show")});g.addEventListener("click",e=>{e.preventDefault(),window.scrollTo({top:0,behavior:"smooth"})});
//# sourceMappingURL=commonHelpers.js.map
